#!/bin/sh

DIRLIST=$(find . -maxdepth 1 -mindepth 1 -type d -exec basename {} \;)
echo "FOUND SAMPLE FOLDERS : $DIRLIST"

for folder in ${DIRLIST[@]}
do
cd $folder
pwd
#trimming 8-50 nt STR 7 /TruSeq3-SE.fa:2:30:7 
for i in `find *.gz`
do
nohup  java -jar /illumina/pipeline/Trimmomatic-0.32/trimmomatic-0.32.jar SE -phred33 $i T0850Q30_$i ILLUMINACLIP:/illumina/pipeline/Trimmomatic-0.32/adapters/TruSeq3-SE.fa:2:30:7 LEADING:30 TRAILING:30 SLIDINGWINDOW:4:15 MINLEN:8 AVGQUAL:30  > nohupT8_STR7$i.out &
sleep 15s
ps -H
done
cd ..
done
